### ISSUE TITLE
The XML document ended unexpectedly.

### ISSUE THREAD

**Issue by Webfeger** [dseph/EwsEditor#18]
Hello,
i'm using Exchange 2016 with CU11 and EWS-Editor Autodiscover Viewer returns only an error message.
Only EWS Schema 2007_SP1 works, all others displays the followed error message.
I already checked http traffic in SoapUI and Exchange returns all messages without issues.

Caught Exception:

    Error Message: The XML document ended unexpectedly.
    Inner Error Message: 
    Stack Trace:    at Microsoft.Exchange.WebServices.Data.EwsXmlReader.Read() in e:\EWSManagedAPI\ews-managed-api\Core\EwsXmlReader.cs:line 174
   at Microsoft.Exchange.WebServices.Autodiscover.WebClientUrlCollection.LoadFromXml(EwsXmlReader reader) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\WebClientUrlCollection.cs:line 57
   at Microsoft.Exchange.WebServices.Autodiscover.GetUserSettingsResponse.ReadSettingFromXml(EwsXmlReader reader) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\Responses\GetUserSettingsResponse.cs:line 200
   at Microsoft.Exchange.WebServices.Autodiscover.GetUserSettingsResponse.LoadUserSettingsFromXml(EwsXmlReader reader) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\Responses\GetUserSettingsResponse.cs:line 160
   at Microsoft.Exchange.WebServices.Autodiscover.GetUserSettingsResponse.LoadFromXml(EwsXmlReader reader, String endElementName) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\Responses\GetUserSettingsResponse.cs:line 126
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverResponseCollection`1.LoadResponseCollectionFromXml(EwsXmlReader reader) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\AutodiscoverResponseCollection.cs:line 117
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverResponseCollection`1.LoadFromXml(EwsXmlReader reader, String endElementName) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\AutodiscoverResponseCollection.cs:line 92
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverRequest.LoadFromXml(EwsXmlReader reader) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\Requests\AutodiscoverRequest.cs:line 588
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverRequest.ReadSoapBody(EwsXmlReader reader) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\Requests\AutodiscoverRequest.cs:line 573
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverRequest.InternalExecute() in e:\EWSManagedAPI\ews-managed-api\Autodiscover\Requests\AutodiscoverRequest.cs:line 159
   at Microsoft.Exchange.WebServices.Autodiscover.GetUserSettingsRequest.Execute() in e:\EWSManagedAPI\ews-managed-api\Autodiscover\Requests\GetUserSettingsRequest.cs:line 110
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetUserSettings(List`1 smtpAddresses, List`1 settings, Nullable`1 requestedVersion, Uri& autodiscoverUrl) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\AutodiscoverService.cs:line 1080
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetSettings[TGetSettingsResponseCollection,TSettingName](List`1 identities, List`1 settings, Nullable`1 requestedVersion, GetSettingsMethod`2 getSettingsMethod, Func`1 getDomainMethod) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\AutodiscoverService.cs:line 1041
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(List`1 smtpAddresses, List`1 settings) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\AutodiscoverService.cs:line 893
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetSoapUserSettings(String smtpAddress, List`1 requestedSettings) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\AutodiscoverService.cs:line 844
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(String userSmtpAddress, UserSettingName[] userSettingNames) in e:\EWSManagedAPI\ews-managed-api\Autodiscover\AutodiscoverService.cs:line 1682
   at EWSEditor.Forms.AutodiscoverViewerForm.AutodiscoverGetUserSettings(AutodiscoverService& service, String sUserSmtpAddress) in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Forms\Discovery\AutodiscoverViewerForm.cs:line 178
    See:

**Comment by dseph** [comment]
That's very strange.  Not seen this before.

**Comment by Webfeger** [comment]
In the meanwhile i found the reason and solved it.
This issue occurs when ExternalURL attribute is not set in exchange. The EWS-Api contains a bug. After excluding or setting this Attribute, everything will wok.

**Comment by dseph** [comment]
Ahhh.  Thank you for the update.
