### ISSUE TITLE
ERROR using TLS on Windows Server 2012R2

### ISSUE THREAD

**Issue by AndTollanin** [dseph/EwsEditor#23]
Is there additional settings for using TLS?
We reconfigured our HTTPS for support TLS on exchange server side. After that on client side ( Windows Server 2012R2 with comleted Windows Update on 09/20/2019 ) we get error:
--------------------------------------------------------------------------------------
Exception details:
Message: The request failed. The underlying connection was closed: An unexpected error occurred on a send.
Type: Microsoft.Exchange.WebServices.Data.ServiceRequestException
Source: Microsoft.Exchange.WebServices
Stack Trace:
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.GetEwsHttpWebResponse(IEwsHttpWebRequest request)
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(IEwsHttpWebRequest& request)
   at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.InternalExecute()
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute()
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalConvertIds(IEnumerable`1 ids, IdFormat destinationFormat, ServiceErrorHandling errorHandling)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.ConvertIds(IEnumerable`1 ids, IdFormat destinationFormat)
   at EWSEditor.Common.Extensions.ExchangeServiceExtensions.TestExchangeService(ExchangeService service) in C:\Work\Sources\ewseditor\EWSEditor_1_20\Common\Extensions\ExchangeServiceExtensions.cs:line 183
   at EWSEditor.Forms.ServiceDialog.BtnOK_Click(Object sender, EventArgs e) in C:\Work\Sources\ewseditor\EWSEditor_1_20\Forms\Dialogs\ServiceDialog.cs:line 278
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Exception details:
Message: The underlying connection was closed: An unexpected error occurred on a send.
Type: System.Net.WebException
Source: System
Stack Trace:
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.Exchange.WebServices.Data.EwsHttpWebRequest.Microsoft.Exchange.WebServices.Data.IEwsHttpWebRequest.GetResponse()
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.GetEwsHttpWebResponse(IEwsHttpWebRequest request)
Exception details:
Message: Authentication failed because the remote party has closed the transport stream.
Type: System.IO.IOException
Source: System
Stack Trace:
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
---------------------------------------------------------------------------
But : on client side with ordinary Windows-10 it works well !

**Comment by dseph** [comment]
Hello,

Try changing to a newer version of .NET.  AFAIK older versions of .NET do not support the newer TLS.  I've run into this with customers and updating resolved the issue.  Remember that EWS Editor uses the EWS managed API and that API uses .NET.  More specifically the EWS calls end up being calls from .NET httpwebrequest.  So, update to a newer version of .NET and the issue will likely go away.

Thank you,

Dan
________________________________

**Comment by dseph** [comment]
Taken care of - Thanks!
