### ISSUE TITLE
Error / Exception on EWS POST

### ISSUE THREAD

**Issue by BernhardK91** [dseph/EwsEditor#25]
Hi there,

when I try to test the EWS of my Exchange 2019 I get the following Error:

![image](https://user-images.githubusercontent.com/5526334/69057898-e1ab2400-0a12-11ea-822a-c504a356dba9.png)

The strange part ist the path in the Stack Trace (I marked it). The path does not exist, as well as the user does not exist. 

Here are the complete exception details as text:
```
Exception details:
Message: Object reference not set to an instance of an object.
Type: System.NullReferenceException
Source: EWSEditor
Stack Trace:
   at EWSEditor.Common.HttpHelper.HtppCall(String sVerb, String sUrl, String sContentType, String sAuthentication, String User, String Password, String Domain, List`1 oHeadersList, WebProxy oWebProxy, String sRequestBody, Int32 iTimeoutSeconds, Boolean bPragmaNoCache, Boolean bTranslateF, Boolean bAllowAutoRedirect, String sUserAgent, String& sRequestHeaders, String& sResult, String& sResponeHeaders, String& sError, String& sResponseStatusCode, Int32& iResponseStatusCodeNumber, String& sResponseStatusDescription) in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Common\UtilityHelpers\HttpHelpler.cs:line 165
   at EWSEditor.Common.PostForm.DoPostByHttpVerb() in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Forms\ToolsForms\PostForm.cs:line 446
   at EWSEditor.Common.PostForm.GoRun_Click(Object sender, EventArgs e) in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Forms\ToolsForms\PostForm.cs:line 124
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Is it a problem of the EWSEditor or how I use it? :-) 

Thank you!

BR
Bernhard

**Comment by BernhardK91** [comment]
Perhaps I found the bug... Is it possible, that "HtppCall()" should be named es "HttpCall()"?

![image](https://user-images.githubusercontent.com/5526334/69058404-e3c1b280-0a13-11ea-810d-8d30b8555941.png)

**EDIT:** It is also called with HtppCall, so that should not cause the error.

**Comment by dseph** [comment]
It should work.  What is the URL an payload?
Please note that I'm about to release 1.21 - it will have an updated version of the EWS Managed API, newer .NET and NuGet packages.

**Comment by BernhardK91** [comment]
The problem was that Exchange 2019 only excepts TLS 1.2 connections, but .NET 4.0 by default uses not TLS 1.2.

To get this running in this environment you have to go into the registry and in this both paths you have to add the following two keys (each with value 1):

**Paths:**
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319

**Keys:**
![image](https://user-images.githubusercontent.com/5526334/69873457-adf4b780-12b8-11ea-8da1-929dca83bf95.png)
Copyable: SchUseStrongCrypto / SystemDefaultTlsVersion
