### ISSUE TITLE
Request Failed 401 Target Principal Name Incorrect

### ISSUE THREAD

**Issue by red-erik** [dseph/EwsEditor#26]
Hello,
when connecting to our internal Exchange server we receive the following:

Exception details:
Message: The request failed. The remote server returned an error: (401) Unauthorized.
Type: Microsoft.Exchange.WebServices.Data.ServiceRequestException
Source: Microsoft.Exchange.WebServices
Stack Trace:
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.GetEwsHttpWebResponse(IEwsHttpWebRequest request) in e:\EWSManagedAPI\ews-managed-api\Core\Requests\ServiceRequestBase.cs:line 750
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(IEwsHttpWebRequest& request) in e:\EWSManagedAPI\ews-managed-api\Core\Requests\ServiceRequestBase.cs:line 640
   at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.InternalExecute() in e:\EWSManagedAPI\ews-managed-api\Core\Requests\SimpleServiceRequestBase.cs:line 55
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute() in e:\EWSManagedAPI\ews-managed-api\Core\Requests\MultiResponseServiceRequest.cs:line 132
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalConvertIds(IEnumerable`1 ids, IdFormat destinationFormat, ServiceErrorHandling errorHandling) in e:\EWSManagedAPI\ews-managed-api\Core\ExchangeService.cs:line 4131
   at Microsoft.Exchange.WebServices.Data.ExchangeService.ConvertIds(IEnumerable`1 ids, IdFormat destinationFormat) in e:\EWSManagedAPI\ews-managed-api\Core\ExchangeService.cs:line 4144
   at EWSEditor.Common.Extensions.ExchangeServiceExtensions.TestExchangeService(ExchangeService service) in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Common\Extensions\ExchangeServiceExtensions.cs:line 183
   at EWSEditor.Exchange.EwsProxyFactory.InitializeWithDefaults(Nullable`1 version, Uri ewsUrl, String autodiscoverAddress) in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Common\EwsProxyFactory.cs:line 491
   at EWSEditor.Exchange.EwsProxyFactory.InitializeWithDefaults() in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Common\EwsProxyFactory.cs:line 451
   at EWSEditor.Forms.FolderTreeForm.OpenDefaultExchangeServiceMenu_Click(Object sender, EventArgs e) in C:\Users\danba\Documents\GitHub\EwsEditor\EWSEditor\Forms\FolderTreeForm.cs:line 876
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Exception details:
Message: The remote server returned an error: (401) Unauthorized.
Type: System.Net.WebException
Source: System
Stack Trace:
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.Exchange.WebServices.Data.EwsHttpWebRequest.Microsoft.Exchange.WebServices.Data.IEwsHttpWebRequest.GetResponse() in e:\EWSManagedAPI\ews-managed-api\Core\EwsHttpWebRequest.cs:line 132
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.GetEwsHttpWebResponse(IEwsHttpWebRequest request) in e:\EWSManagedAPI\ews-managed-api\Core\Requests\ServiceRequestBase.cs:line 740
Exception details:
Message: The target principal name is incorrect
Type: System.ComponentModel.Win32Exception
Source: System
Stack Trace:
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatus& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.NegotiateClient.DoAuthenticate(String challenge, WebRequest webRequest, ICredentials credentials, Boolean preAuthenticate)
   at System.Net.NegotiateClient.Authenticate(String challenge, WebRequest webRequest, ICredentials credentials)
   at System.Net.AuthenticationManagerDefault.Authenticate(String challenge, WebRequest request, ICredentials credentials)
   at System.Net.AuthenticationState.AttemptAuthenticate(HttpWebRequest httpWebRequest, ICredentials authInfo)
   at System.Net.HttpWebRequest.CheckResubmitForAuth()
   at System.Net.HttpWebRequest.CheckResubmit(Exception& e, Boolean& disableUpload)

Is it normal?

Regards,

Red.

**Comment by dseph** [comment]
It does not like your credentials it seems.  There is no way to tell whats happening just with an error stack.
