### ISSUE TITLE
How is OAuth expected to work?

### ISSUE THREAD

**Issue by dcormier** [dseph/EwsEditor#33]
What's needed to make OAuth work with this? I've put in the client ID of the `365 app I'm using, but there is no apparent place to put the secret. As a result, when I go through the OAuth flow with the current release (1.21) I get this:

`The request body must contain the following parameter: 'client_assertion' or 'client_secret'.`

I'm not sure what to do to get past this.

Here's the full error:

```text
Exception details:
Message: One or more errors occurred.
Type: System.AggregateException
Source: mscorlib
Stack Trace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at EWSEditor.Common.AuthenticationHelper.Do_OAuth(String& MailboxBeingAccessed, String& AccountAccessingMailbox, String sAuthority, String sAppId, String sRedirectURL, String sServername, String& sBearerToken, PromptBehavior oPromptBehavior) in C:\this\GitHub\EwsEditor\EWSEditor\Common\EwsHelpers\AuthenticationHelper.cs:line 65
   at EWSEditor.Common.AuthenticationHelper.Do_OAuth(String& MailboxBeingAccessed, String& AccountAccessingMailbox, String sAuthority, String sAppId, String sRedirectURL, String sServername, String& sBearerToken) in C:\this\GitHub\EwsEditor\EWSEditor\Common\EwsHelpers\AuthenticationHelper.cs:line 83
   at EWSEditor.Forms.ServiceDialog.BtnOK_Click(Object sender, EventArgs e) in C:\this\GitHub\EwsEditor\EWSEditor\Forms\Dialogs\ServiceDialog.cs:line 248
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Exception details:
Message: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: e7002e4c-d45a-4881-82fd-589d4a5aac00
Correlation ID: 66516535-b808-4594-996f-48e014a5d9fa
Timestamp: 2020-09-24 13:24:02Z
Type: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException
Source: Microsoft.IdentityModel.Clients.ActiveDirectory
Stack Trace:
   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Core\OAuth2\OAuthClient.cs:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__17`1.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Core\OAuth2\OAuthClient.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__75.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 405
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__72.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__62.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__60.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Internal\Flows\AcquireTokenHandlerBase.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__42.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\AuthenticationContext.cs:line 608
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__32.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\AuthenticationContext.cs:line 407
Exception details:
Message: Response status code does not indicate success: 401 (Unauthorized).
Type: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException
Source: Microsoft.IdentityModel.Clients.ActiveDirectory
Stack Trace:
   at Microsoft.Identity.Core.OAuth2.OAuthClient.<GetResponseAsync>d__18`1.MoveNext() in D:\a\1\s\src\Microsoft.IdentityModel.Clients.ActiveDirectory\Core\OAuth2\OAuthClient.cs:line 62
```

**Comment by YuriySamorodov** [comment]
@dcormier Have the same issue. Were you able to resolve it?

**Comment by dseph** [comment]
it does not support app flow at this time.  You can add a bearer token as a header for app flow. You can get a token by using something like postman.  I hope to have time to add this as feature in the near future.

**Comment by dseph** [comment]
Hello.  I've added code for oAuth2 flows - delegate and app credentials.  If you need to use oAuth in the Post window then log in and copy the token from the oAuth window found under the Tools menu and add it in as a header.  In Global Options you can turn off logging the oAuth credentail to the log - however, you can still copy it from the Tools menu.
